# Generated by Django 5.1 on 2024-08-10 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=200, unique=True)),
                ('house_name', models.CharField(blank=True, max_length=200, null=True)),
                ('house_owner', models.CharField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(blank=True, choices=[('VALLIKAD', 'Vallikad'), ('VELLIKULANGARA', 'Vellikulangara')], max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('no_of_members', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(blank=True, editable=False, max_length=400)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('marital_status', models.BooleanField(choices=[(True, 'Married'), (False, 'Single')], default=False)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, choices=[('PAT', 'Patients'), ('DVC', 'Divorced'), ('WID', 'Widow'), ('NVR', 'Never Married')], max_length=3, null=True)),
                ('remarks_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='house_management.house')),
            ],
        ),
    ]
