# Generated by Django 5.1 on 2024-08-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
