# Generated by Django 5.1 on 2025-06-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_management', '0002_house_remarks_member_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='education',
            field=models.CharField(blank=True, choices=[('PR', 'Primary School'), ('HS', 'High School'), ('SC', 'Secondary School'), ('UG', 'Undergraduate Degree'), ('PG', 'Postgraduate Degree'), ('PH', 'PhD'), ('NT', 'No Formal Education'), ('OT', 'Other')], max_length=2, null=True),
        ),
    ]
